version: "3.1"
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullstack_laboratorio
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  db_data:
